### PR TITLE
feat: added __call__, reduced dependancy on openai

### PR DESCRIPTION
**Pull request by Kacper-W-Kozdon**
As in the title. PR **not yet tested**. Async not yet finished. Change suggestions are welcome :)

### CODE REVIEW

**Comment by Kacper-W-Kozdon** [comment]
@OscarArroyoVega take a look, please- and double check if it works; without caching, it's much simpler. I left Kato's approach in place, too.

**Review by OscarArroyoVega — COMMENTED** [review]
Reviewed! now PR to main_branch in this fork will be approved. Then when merging to the feature_branch conflicts will be solved there. In this way contributors along the process will have visibility. 
Thank you :)

**Review by OscarArroyoVega — COMMENTED** [review]
Reviewed, now PR will be approved. Then when merging with the feature_branch I will change the file name to unify.py instead of unify_dsp.py (thanks for the option). In this way we will be able to solve conflicts maintaining the contributors visibility.
Thank  you :)

**Comment by OscarArroyoVega** [comment]
> @OscarArroyoVega take a look, please- and double check if it works; without caching, it's much simpler. I left Kato's approach in place, too.

Thank you for adding Kato's contributions in the PR!!

**Pull request merged**
