### PR TITLE
added the documentation for simplicity

### PR DESCRIPTION
**Pull request by Sanjay8602**
Nothing just added the documentation for simplicity and easy to understand

### CODE REVIEW

**Comment by Sanjay8602** [comment]
@OscarArroyoVega have a look

**Review by OscarArroyoVega — CHANGES_REQUESTED** [review]
Hello Sanjay,Thank you! if you take a look to unifyai style (also in dspy) they don't add "Args" to the docstring, just a single line description. 
Just remove the "args" for approval :)

**Comment by Sanjay8602** [comment]
Ok

**Review by Sanjay8602 — COMMENTED** [review]
Now looks similar. I added the "args" and now deleted

**Review by OscarArroyoVega — APPROVED** [review]
thank you!!!

**Pull request merged**
